CREATE TABLE test (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  "timestamp" TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
  class INTEGER NOT NULL,
  version INTEGER NOT NULL,
  word_id INTEGER NOT NULL,
  correct INTEGER NOT NULL
);
